apiVersion: apps/v1
kind: Deployment
metadata:
  name: recrawler-deployment
  labels:
    app: recrawler
spec:
  selector:
    matchLabels:
      app: recrawler
      role: web
  template:
    metadata:
      labels:
        app: recrawler
        role: web
    spec:
      containers:
      - image: registry.openculinary.org/reciperadar/recrawler
        imagePullPolicy: IfNotPresent
        name: recrawler
        ports:
        - containerPort: 8000
        env:
          - name: MOJEEK_API_KEY
            valueFrom:
              secretKeyRef:
                name: recrawler-client-credentials
                key: mojeek-api-key
          - name: RECRAWLS_PER_MILLE
            value: '100'
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/tmp
          name: var-tmp
      volumes:
      - name: var-tmp
        emptyDir:
          medium: "Memory"
          sizeLimit: "128Mi"
