apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recrawler-ingress
spec:
  rules:
  - host: recrawler
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: recrawler-service
            port:
              number: 80
